#!/bin/bash

function check() {
	if ! curl --silent -m 30 http://twistedmatrix.com/trac/ > current-page || grep "Could not connect" current-page > /dev/null; then
		date >> ~/log/monitor-restarts.log
		~/bin/restart >> ~/log/monitor-restarts.log 2>&1
	fi
	rm current-page
}

while :; do
	check >> ~/log/monitor-debug.log
	sleep 30
done
