#!/bin/bash

ulimit -Sm $((1024 * 256))
ulimit -Sm $((1024 * 256))
ulimit -Sc unlimited

~pypy/bin/twistd \
	--pidfile ~/run/trac-infra.pid \
	--logfile ~/log/trac-infra.log \
	--python ~/config/server.tac
